version: "3.4"

services:
  ghost:
    networks:
    - internal
    image: ghost:5-alpine
    restart: unless-stopped
    ports:
      - 33291:2368
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ghost
      database__connection__password: ghost-docker
      database__connection__database: ghost
      url: https://blog.andreijiroh.dev
    env_file: .env.ghost.decrypted
    volumes:
      - ./data/ghost:/var/lib/ghost/content
    depends_on:
      - mysql

  hedgedoc:
    networks:
      - internal
    image: quay.io/hedgedoc/hedgedoc:1.10.0
    environment:
      - CMD_DOMAIN=notepad.recaptime.dev
      - CMD_URL_ADDPORT=false
      - CMD_ALLOW_FREEURL=true
      - CMD_ALLOW_GRAVATAR=true
      - CMD_EMAIL=false
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_REQUIRE_FREEURL_AUTHENTICATION=true
      - CMD_CSP_ALLOW_PDF_EMBED=false
    volumes:
      - ./hedgedoc:/deploydocs
    env_file: .env.hedgedoc.decrypted
    extra_hosts:
    - "host.docker.internal:host-gateway"
    #- "postgres.hackclub.app:host-gateway"
    ports:
      - 34171:3000

  mysql:
    #domainname: mysql.internal
    networks:
    - internal
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql-chaos
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost-docker
      MYSQL_DATABASE: ghost
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  internal:
    attachable: true

